/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WetRouteImport } from './routes/wet'
import { Route as TutorsDiaryRouteImport } from './routes/tutors-diary'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as TextbookRouteImport } from './routes/textbook'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as TeacherTimetableRouteImport } from './routes/teacher-timetable'
import { Route as TeacherFeedbackRouteImport } from './routes/teacher-feedback'
import { Route as TeacherExamsRouteImport } from './routes/teacher-exams'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher-attendance'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as QuranRouteImport } from './routes/quran'
import { Route as PyqRouteImport } from './routes/pyq'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrayerAttendanceRouteImport } from './routes/prayer-attendance'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as ParentChildResultsRouteImport } from './routes/parent-child-results'
import { Route as ParentChildLeaveRouteImport } from './routes/parent-child-leave'
import { Route as ParentChildAttendanceRouteImport } from './routes/parent-child-attendance'
import { Route as PagesRouteImport } from './routes/pages'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MyTutorsDiaryRouteImport } from './routes/my-tutors-diary'
import { Route as MoralRouteImport } from './routes/moral'
import { Route as MonttalkRouteImport } from './routes/monttalk'
import { Route as MocktestRouteImport } from './routes/mocktest'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaveRouteImport } from './routes/leave'
import { Route as IdcardRouteImport } from './routes/idcard'
import { Route as HostelRouteImport } from './routes/hostel'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as DhikrRouteImport } from './routes/dhikr'
import { Route as DetRouteImport } from './routes/det'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin/index'
import { Route as SuperadminTeachersRouteImport } from './routes/superadmin/teachers'
import { Route as SuperadminStudentsRouteImport } from './routes/superadmin/students'
import { Route as SuperadminParentsRouteImport } from './routes/superadmin/parents'
import { Route as SuperadminBatchesRouteImport } from './routes/superadmin/batches'
import { Route as SuperadminAddTeacherRouteImport } from './routes/superadmin/add-teacher'

const WetRoute = WetRouteImport.update({
  id: '/wet',
  path: '/wet',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorsDiaryRoute = TutorsDiaryRouteImport.update({
  id: '/tutors-diary',
  path: '/tutors-diary',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const TextbookRoute = TextbookRouteImport.update({
  id: '/textbook',
  path: '/textbook',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherTimetableRoute = TeacherTimetableRouteImport.update({
  id: '/teacher-timetable',
  path: '/teacher-timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherFeedbackRoute = TeacherFeedbackRouteImport.update({
  id: '/teacher-feedback',
  path: '/teacher-feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherExamsRoute = TeacherExamsRouteImport.update({
  id: '/teacher-exams',
  path: '/teacher-exams',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/teacher-attendance',
  path: '/teacher-attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranRoute = QuranRouteImport.update({
  id: '/quran',
  path: '/quran',
  getParentRoute: () => rootRouteImport,
} as any)
const PyqRoute = PyqRouteImport.update({
  id: '/pyq',
  path: '/pyq',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerAttendanceRoute = PrayerAttendanceRouteImport.update({
  id: '/prayer-attendance',
  path: '/prayer-attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentChildResultsRoute = ParentChildResultsRouteImport.update({
  id: '/parent-child-results',
  path: '/parent-child-results',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentChildLeaveRoute = ParentChildLeaveRouteImport.update({
  id: '/parent-child-leave',
  path: '/parent-child-leave',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentChildAttendanceRoute = ParentChildAttendanceRouteImport.update({
  id: '/parent-child-attendance',
  path: '/parent-child-attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRoute = PagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTutorsDiaryRoute = MyTutorsDiaryRouteImport.update({
  id: '/my-tutors-diary',
  path: '/my-tutors-diary',
  getParentRoute: () => rootRouteImport,
} as any)
const MoralRoute = MoralRouteImport.update({
  id: '/moral',
  path: '/moral',
  getParentRoute: () => rootRouteImport,
} as any)
const MonttalkRoute = MonttalkRouteImport.update({
  id: '/monttalk',
  path: '/monttalk',
  getParentRoute: () => rootRouteImport,
} as any)
const MocktestRoute = MocktestRouteImport.update({
  id: '/mocktest',
  path: '/mocktest',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveRoute = LeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const IdcardRoute = IdcardRouteImport.update({
  id: '/idcard',
  path: '/idcard',
  getParentRoute: () => rootRouteImport,
} as any)
const HostelRoute = HostelRouteImport.update({
  id: '/hostel',
  path: '/hostel',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const DhikrRoute = DhikrRouteImport.update({
  id: '/dhikr',
  path: '/dhikr',
  getParentRoute: () => rootRouteImport,
} as any)
const DetRoute = DetRouteImport.update({
  id: '/det',
  path: '/det',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/superadmin/',
  path: '/superadmin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminTeachersRoute = SuperadminTeachersRouteImport.update({
  id: '/superadmin/teachers',
  path: '/superadmin/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminStudentsRoute = SuperadminStudentsRouteImport.update({
  id: '/superadmin/students',
  path: '/superadmin/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminParentsRoute = SuperadminParentsRouteImport.update({
  id: '/superadmin/parents',
  path: '/superadmin/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminBatchesRoute = SuperadminBatchesRouteImport.update({
  id: '/superadmin/batches',
  path: '/superadmin/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminAddTeacherRoute = SuperadminAddTeacherRouteImport.update({
  id: '/superadmin/add-teacher',
  path: '/superadmin/add-teacher',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academics': typeof AcademicsRoute
  '/ai': typeof AiRoute
  '/attendance': typeof AttendanceRoute
  '/calendar': typeof CalendarRoute
  '/det': typeof DetRoute
  '/dhikr': typeof DhikrRoute
  '/exams': typeof ExamsRoute
  '/feedback': typeof FeedbackRoute
  '/hostel': typeof HostelRoute
  '/idcard': typeof IdcardRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/mocktest': typeof MocktestRoute
  '/monttalk': typeof MonttalkRoute
  '/moral': typeof MoralRoute
  '/my-tutors-diary': typeof MyTutorsDiaryRoute
  '/notifications': typeof NotificationsRoute
  '/pages': typeof PagesRoute
  '/parent-child-attendance': typeof ParentChildAttendanceRoute
  '/parent-child-leave': typeof ParentChildLeaveRoute
  '/parent-child-results': typeof ParentChildResultsRoute
  '/parents': typeof ParentsRoute
  '/prayer-attendance': typeof PrayerAttendanceRoute
  '/profile': typeof ProfileRoute
  '/pyq': typeof PyqRoute
  '/quran': typeof QuranRoute
  '/results': typeof ResultsRoute
  '/teacher-attendance': typeof TeacherAttendanceRoute
  '/teacher-exams': typeof TeacherExamsRoute
  '/teacher-feedback': typeof TeacherFeedbackRoute
  '/teacher-timetable': typeof TeacherTimetableRoute
  '/teachers': typeof TeachersRoute
  '/textbook': typeof TextbookRoute
  '/timetable': typeof TimetableRoute
  '/tutors-diary': typeof TutorsDiaryRoute
  '/wet': typeof WetRoute
  '/superadmin/add-teacher': typeof SuperadminAddTeacherRoute
  '/superadmin/batches': typeof SuperadminBatchesRoute
  '/superadmin/parents': typeof SuperadminParentsRoute
  '/superadmin/students': typeof SuperadminStudentsRoute
  '/superadmin/teachers': typeof SuperadminTeachersRoute
  '/superadmin/': typeof SuperadminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academics': typeof AcademicsRoute
  '/ai': typeof AiRoute
  '/attendance': typeof AttendanceRoute
  '/calendar': typeof CalendarRoute
  '/det': typeof DetRoute
  '/dhikr': typeof DhikrRoute
  '/exams': typeof ExamsRoute
  '/feedback': typeof FeedbackRoute
  '/hostel': typeof HostelRoute
  '/idcard': typeof IdcardRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/mocktest': typeof MocktestRoute
  '/monttalk': typeof MonttalkRoute
  '/moral': typeof MoralRoute
  '/my-tutors-diary': typeof MyTutorsDiaryRoute
  '/notifications': typeof NotificationsRoute
  '/pages': typeof PagesRoute
  '/parent-child-attendance': typeof ParentChildAttendanceRoute
  '/parent-child-leave': typeof ParentChildLeaveRoute
  '/parent-child-results': typeof ParentChildResultsRoute
  '/parents': typeof ParentsRoute
  '/prayer-attendance': typeof PrayerAttendanceRoute
  '/profile': typeof ProfileRoute
  '/pyq': typeof PyqRoute
  '/quran': typeof QuranRoute
  '/results': typeof ResultsRoute
  '/teacher-attendance': typeof TeacherAttendanceRoute
  '/teacher-exams': typeof TeacherExamsRoute
  '/teacher-feedback': typeof TeacherFeedbackRoute
  '/teacher-timetable': typeof TeacherTimetableRoute
  '/teachers': typeof TeachersRoute
  '/textbook': typeof TextbookRoute
  '/timetable': typeof TimetableRoute
  '/tutors-diary': typeof TutorsDiaryRoute
  '/wet': typeof WetRoute
  '/superadmin/add-teacher': typeof SuperadminAddTeacherRoute
  '/superadmin/batches': typeof SuperadminBatchesRoute
  '/superadmin/parents': typeof SuperadminParentsRoute
  '/superadmin/students': typeof SuperadminStudentsRoute
  '/superadmin/teachers': typeof SuperadminTeachersRoute
  '/superadmin': typeof SuperadminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academics': typeof AcademicsRoute
  '/ai': typeof AiRoute
  '/attendance': typeof AttendanceRoute
  '/calendar': typeof CalendarRoute
  '/det': typeof DetRoute
  '/dhikr': typeof DhikrRoute
  '/exams': typeof ExamsRoute
  '/feedback': typeof FeedbackRoute
  '/hostel': typeof HostelRoute
  '/idcard': typeof IdcardRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/mocktest': typeof MocktestRoute
  '/monttalk': typeof MonttalkRoute
  '/moral': typeof MoralRoute
  '/my-tutors-diary': typeof MyTutorsDiaryRoute
  '/notifications': typeof NotificationsRoute
  '/pages': typeof PagesRoute
  '/parent-child-attendance': typeof ParentChildAttendanceRoute
  '/parent-child-leave': typeof ParentChildLeaveRoute
  '/parent-child-results': typeof ParentChildResultsRoute
  '/parents': typeof ParentsRoute
  '/prayer-attendance': typeof PrayerAttendanceRoute
  '/profile': typeof ProfileRoute
  '/pyq': typeof PyqRoute
  '/quran': typeof QuranRoute
  '/results': typeof ResultsRoute
  '/teacher-attendance': typeof TeacherAttendanceRoute
  '/teacher-exams': typeof TeacherExamsRoute
  '/teacher-feedback': typeof TeacherFeedbackRoute
  '/teacher-timetable': typeof TeacherTimetableRoute
  '/teachers': typeof TeachersRoute
  '/textbook': typeof TextbookRoute
  '/timetable': typeof TimetableRoute
  '/tutors-diary': typeof TutorsDiaryRoute
  '/wet': typeof WetRoute
  '/superadmin/add-teacher': typeof SuperadminAddTeacherRoute
  '/superadmin/batches': typeof SuperadminBatchesRoute
  '/superadmin/parents': typeof SuperadminParentsRoute
  '/superadmin/students': typeof SuperadminStudentsRoute
  '/superadmin/teachers': typeof SuperadminTeachersRoute
  '/superadmin/': typeof SuperadminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academics'
    | '/ai'
    | '/attendance'
    | '/calendar'
    | '/det'
    | '/dhikr'
    | '/exams'
    | '/feedback'
    | '/hostel'
    | '/idcard'
    | '/leave'
    | '/login'
    | '/mocktest'
    | '/monttalk'
    | '/moral'
    | '/my-tutors-diary'
    | '/notifications'
    | '/pages'
    | '/parent-child-attendance'
    | '/parent-child-leave'
    | '/parent-child-results'
    | '/parents'
    | '/prayer-attendance'
    | '/profile'
    | '/pyq'
    | '/quran'
    | '/results'
    | '/teacher-attendance'
    | '/teacher-exams'
    | '/teacher-feedback'
    | '/teacher-timetable'
    | '/teachers'
    | '/textbook'
    | '/timetable'
    | '/tutors-diary'
    | '/wet'
    | '/superadmin/add-teacher'
    | '/superadmin/batches'
    | '/superadmin/parents'
    | '/superadmin/students'
    | '/superadmin/teachers'
    | '/superadmin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academics'
    | '/ai'
    | '/attendance'
    | '/calendar'
    | '/det'
    | '/dhikr'
    | '/exams'
    | '/feedback'
    | '/hostel'
    | '/idcard'
    | '/leave'
    | '/login'
    | '/mocktest'
    | '/monttalk'
    | '/moral'
    | '/my-tutors-diary'
    | '/notifications'
    | '/pages'
    | '/parent-child-attendance'
    | '/parent-child-leave'
    | '/parent-child-results'
    | '/parents'
    | '/prayer-attendance'
    | '/profile'
    | '/pyq'
    | '/quran'
    | '/results'
    | '/teacher-attendance'
    | '/teacher-exams'
    | '/teacher-feedback'
    | '/teacher-timetable'
    | '/teachers'
    | '/textbook'
    | '/timetable'
    | '/tutors-diary'
    | '/wet'
    | '/superadmin/add-teacher'
    | '/superadmin/batches'
    | '/superadmin/parents'
    | '/superadmin/students'
    | '/superadmin/teachers'
    | '/superadmin'
  id:
    | '__root__'
    | '/'
    | '/academics'
    | '/ai'
    | '/attendance'
    | '/calendar'
    | '/det'
    | '/dhikr'
    | '/exams'
    | '/feedback'
    | '/hostel'
    | '/idcard'
    | '/leave'
    | '/login'
    | '/mocktest'
    | '/monttalk'
    | '/moral'
    | '/my-tutors-diary'
    | '/notifications'
    | '/pages'
    | '/parent-child-attendance'
    | '/parent-child-leave'
    | '/parent-child-results'
    | '/parents'
    | '/prayer-attendance'
    | '/profile'
    | '/pyq'
    | '/quran'
    | '/results'
    | '/teacher-attendance'
    | '/teacher-exams'
    | '/teacher-feedback'
    | '/teacher-timetable'
    | '/teachers'
    | '/textbook'
    | '/timetable'
    | '/tutors-diary'
    | '/wet'
    | '/superadmin/add-teacher'
    | '/superadmin/batches'
    | '/superadmin/parents'
    | '/superadmin/students'
    | '/superadmin/teachers'
    | '/superadmin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademicsRoute: typeof AcademicsRoute
  AiRoute: typeof AiRoute
  AttendanceRoute: typeof AttendanceRoute
  CalendarRoute: typeof CalendarRoute
  DetRoute: typeof DetRoute
  DhikrRoute: typeof DhikrRoute
  ExamsRoute: typeof ExamsRoute
  FeedbackRoute: typeof FeedbackRoute
  HostelRoute: typeof HostelRoute
  IdcardRoute: typeof IdcardRoute
  LeaveRoute: typeof LeaveRoute
  LoginRoute: typeof LoginRoute
  MocktestRoute: typeof MocktestRoute
  MonttalkRoute: typeof MonttalkRoute
  MoralRoute: typeof MoralRoute
  MyTutorsDiaryRoute: typeof MyTutorsDiaryRoute
  NotificationsRoute: typeof NotificationsRoute
  PagesRoute: typeof PagesRoute
  ParentChildAttendanceRoute: typeof ParentChildAttendanceRoute
  ParentChildLeaveRoute: typeof ParentChildLeaveRoute
  ParentChildResultsRoute: typeof ParentChildResultsRoute
  ParentsRoute: typeof ParentsRoute
  PrayerAttendanceRoute: typeof PrayerAttendanceRoute
  ProfileRoute: typeof ProfileRoute
  PyqRoute: typeof PyqRoute
  QuranRoute: typeof QuranRoute
  ResultsRoute: typeof ResultsRoute
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
  TeacherExamsRoute: typeof TeacherExamsRoute
  TeacherFeedbackRoute: typeof TeacherFeedbackRoute
  TeacherTimetableRoute: typeof TeacherTimetableRoute
  TeachersRoute: typeof TeachersRoute
  TextbookRoute: typeof TextbookRoute
  TimetableRoute: typeof TimetableRoute
  TutorsDiaryRoute: typeof TutorsDiaryRoute
  WetRoute: typeof WetRoute
  SuperadminAddTeacherRoute: typeof SuperadminAddTeacherRoute
  SuperadminBatchesRoute: typeof SuperadminBatchesRoute
  SuperadminParentsRoute: typeof SuperadminParentsRoute
  SuperadminStudentsRoute: typeof SuperadminStudentsRoute
  SuperadminTeachersRoute: typeof SuperadminTeachersRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wet': {
      id: '/wet'
      path: '/wet'
      fullPath: '/wet'
      preLoaderRoute: typeof WetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutors-diary': {
      id: '/tutors-diary'
      path: '/tutors-diary'
      fullPath: '/tutors-diary'
      preLoaderRoute: typeof TutorsDiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/textbook': {
      id: '/textbook'
      path: '/textbook'
      fullPath: '/textbook'
      preLoaderRoute: typeof TextbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-timetable': {
      id: '/teacher-timetable'
      path: '/teacher-timetable'
      fullPath: '/teacher-timetable'
      preLoaderRoute: typeof TeacherTimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-feedback': {
      id: '/teacher-feedback'
      path: '/teacher-feedback'
      fullPath: '/teacher-feedback'
      preLoaderRoute: typeof TeacherFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-exams': {
      id: '/teacher-exams'
      path: '/teacher-exams'
      fullPath: '/teacher-exams'
      preLoaderRoute: typeof TeacherExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-attendance': {
      id: '/teacher-attendance'
      path: '/teacher-attendance'
      fullPath: '/teacher-attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran': {
      id: '/quran'
      path: '/quran'
      fullPath: '/quran'
      preLoaderRoute: typeof QuranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pyq': {
      id: '/pyq'
      path: '/pyq'
      fullPath: '/pyq'
      preLoaderRoute: typeof PyqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer-attendance': {
      id: '/prayer-attendance'
      path: '/prayer-attendance'
      fullPath: '/prayer-attendance'
      preLoaderRoute: typeof PrayerAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent-child-results': {
      id: '/parent-child-results'
      path: '/parent-child-results'
      fullPath: '/parent-child-results'
      preLoaderRoute: typeof ParentChildResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent-child-leave': {
      id: '/parent-child-leave'
      path: '/parent-child-leave'
      fullPath: '/parent-child-leave'
      preLoaderRoute: typeof ParentChildLeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent-child-attendance': {
      id: '/parent-child-attendance'
      path: '/parent-child-attendance'
      fullPath: '/parent-child-attendance'
      preLoaderRoute: typeof ParentChildAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages': {
      id: '/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof PagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tutors-diary': {
      id: '/my-tutors-diary'
      path: '/my-tutors-diary'
      fullPath: '/my-tutors-diary'
      preLoaderRoute: typeof MyTutorsDiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moral': {
      id: '/moral'
      path: '/moral'
      fullPath: '/moral'
      preLoaderRoute: typeof MoralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monttalk': {
      id: '/monttalk'
      path: '/monttalk'
      fullPath: '/monttalk'
      preLoaderRoute: typeof MonttalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mocktest': {
      id: '/mocktest'
      path: '/mocktest'
      fullPath: '/mocktest'
      preLoaderRoute: typeof MocktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave': {
      id: '/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof LeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idcard': {
      id: '/idcard'
      path: '/idcard'
      fullPath: '/idcard'
      preLoaderRoute: typeof IdcardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hostel': {
      id: '/hostel'
      path: '/hostel'
      fullPath: '/hostel'
      preLoaderRoute: typeof HostelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dhikr': {
      id: '/dhikr'
      path: '/dhikr'
      fullPath: '/dhikr'
      preLoaderRoute: typeof DhikrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/det': {
      id: '/det'
      path: '/det'
      fullPath: '/det'
      preLoaderRoute: typeof DetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/superadmin'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/teachers': {
      id: '/superadmin/teachers'
      path: '/superadmin/teachers'
      fullPath: '/superadmin/teachers'
      preLoaderRoute: typeof SuperadminTeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/students': {
      id: '/superadmin/students'
      path: '/superadmin/students'
      fullPath: '/superadmin/students'
      preLoaderRoute: typeof SuperadminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/parents': {
      id: '/superadmin/parents'
      path: '/superadmin/parents'
      fullPath: '/superadmin/parents'
      preLoaderRoute: typeof SuperadminParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/batches': {
      id: '/superadmin/batches'
      path: '/superadmin/batches'
      fullPath: '/superadmin/batches'
      preLoaderRoute: typeof SuperadminBatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/add-teacher': {
      id: '/superadmin/add-teacher'
      path: '/superadmin/add-teacher'
      fullPath: '/superadmin/add-teacher'
      preLoaderRoute: typeof SuperadminAddTeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademicsRoute: AcademicsRoute,
  AiRoute: AiRoute,
  AttendanceRoute: AttendanceRoute,
  CalendarRoute: CalendarRoute,
  DetRoute: DetRoute,
  DhikrRoute: DhikrRoute,
  ExamsRoute: ExamsRoute,
  FeedbackRoute: FeedbackRoute,
  HostelRoute: HostelRoute,
  IdcardRoute: IdcardRoute,
  LeaveRoute: LeaveRoute,
  LoginRoute: LoginRoute,
  MocktestRoute: MocktestRoute,
  MonttalkRoute: MonttalkRoute,
  MoralRoute: MoralRoute,
  MyTutorsDiaryRoute: MyTutorsDiaryRoute,
  NotificationsRoute: NotificationsRoute,
  PagesRoute: PagesRoute,
  ParentChildAttendanceRoute: ParentChildAttendanceRoute,
  ParentChildLeaveRoute: ParentChildLeaveRoute,
  ParentChildResultsRoute: ParentChildResultsRoute,
  ParentsRoute: ParentsRoute,
  PrayerAttendanceRoute: PrayerAttendanceRoute,
  ProfileRoute: ProfileRoute,
  PyqRoute: PyqRoute,
  QuranRoute: QuranRoute,
  ResultsRoute: ResultsRoute,
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherExamsRoute: TeacherExamsRoute,
  TeacherFeedbackRoute: TeacherFeedbackRoute,
  TeacherTimetableRoute: TeacherTimetableRoute,
  TeachersRoute: TeachersRoute,
  TextbookRoute: TextbookRoute,
  TimetableRoute: TimetableRoute,
  TutorsDiaryRoute: TutorsDiaryRoute,
  WetRoute: WetRoute,
  SuperadminAddTeacherRoute: SuperadminAddTeacherRoute,
  SuperadminBatchesRoute: SuperadminBatchesRoute,
  SuperadminParentsRoute: SuperadminParentsRoute,
  SuperadminStudentsRoute: SuperadminStudentsRoute,
  SuperadminTeachersRoute: SuperadminTeachersRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
